### ISSUE TITLE
importing the library

### ISSUE THREAD

**Issue by Coserix** [tyczj/ExtendedCalendarView#105]
Is there a guide step to step that explain how to import the library for the newbies in android studio? 
thx

**Comment by lankesh** [comment]
I am a newbie to android as well.
And I am using android studio.
I have been struggling to get this imported in my project as well.
It would be very helpfull if you provided a step by step guide for newbiews as well.

Thank you i advance :)

Can you provide a gradle import for ease of use in Android studio
