### ISSUE TITLE
The following classes could not be found/instantiated

### ISSUE THREAD

**Issue by iASCE** [tyczj/ExtendedCalendarView#17]
I'm trying to import your library to my project

i'm using eclipse, and i did this by going to my project properties > add library > android classpath container > ExtendedCalendarView. 

then I added the snippet you used in "Usage" to my layout.xml, but i get this error:
The following classes could not be found.

and when i use only the .jar file that is in the bin folder i get this error:
The following classes could not be instantiated.

how exactly do i import this library ? and when i do, how do i create an instance of this class without getting "instantiation" error ?

**Comment by Tazuki** [comment]
Like i said in other issues. Make sure that you uncheck the checkbox "copy project into workspace"!!! =)

**Comment by XNepster** [comment]
Make sure you have checked the library you imported under Project->Properties->JavaBuildPath->order And Export  And check the library you imported As suggested by Tazuki
