### ISSUE TITLE
Problem with implementation 

### ISSUE THREAD

**Issue by euronix** [tyczj/ExtendedCalendarView#6]
Hello,
I have a problem with implementation in my project. 
Here is my error:
02-10 15:03:35.608: E/AndroidRuntime(26933): Caused by: java.lang.SecurityException: Permission Denial: opening provider com.tyczj.extendedcalendarview.CalendarProvider from ProcessRecord{4561ad78 26933:cz.titio.calnedartest/u0a10104} (pid=26933, uid=10104) that is not exported from uid 10079

Thanks for you help!

**Comment by GouthamIyyapan** [comment]
java.lang.SecurityException: Permission Denial: opening provider com.tyczj.extendedcalendarview.CalendarProvider from ProcessRecord{38c10969 7019:com.noroc.binge.debug/u0a267} (pid=7019, uid=10267) requires signature or signature

Error not resolved by any of the above solutions. Please reopen and provide a solution.

**Comment by ghost** [comment]
java.lang.SecurityException: Permission Denial: opening provider com.tyczj.extendedcalendarview.CalendarProvider from ProcessRecord{42aa0100 21642:com.example.calendarpoc/u0a202} (pid=21642, uid=10202) that is not exported from uid 10198
