### ISSUE TITLE
How to change Calendar month text color?

### ISSUE THREAD

**Issue by suddyv519** [tyczj/ExtendedCalendarView#80]
I was able to edit the color for the left and right arrows to go between the different months? But how do I edit the text color for the months themselves?

**Comment by suddyv519** [comment]
bump

**Comment by ghost** [comment]
setMonthTextBackgroundColor() is there in ExtendedCalendarView class just check that one and call that method it will change the background color

**Comment by suddyv519** [comment]
Where should I call the method?

**Comment by ghost** [comment]
It can be used anywhere(where you want means when you are clicking on some button you want to change the background then you can use)

otherwise if you want to change background color at displaying of calendar then you can use inside onCreate() of your activity(where your are using calendar).
