### ISSUE TITLE
get  Installation error: INSTALL_FAILED_CONFLICTING_PROVIDER error

### ISSUE THREAD

**Issue by mohsin111** [tyczj/ExtendedCalendarView#81]
Installation error: INSTALL_FAILED_CONFLICTING_PROVIDER while providing value of authoritites in Android Mainfest file .

**Comment by ghost** [comment]
"Remove already installed application and run again" because already provider is there so it is shown error

**Comment by mohsin111** [comment]
got it.It runs fine. Thank you
