### ISSUE TITLE
'wrap_content' for android:layout_height in xml does not works

### ISSUE THREAD

**Issue by essencer** [tyczj/ExtendedCalendarView#83]
<com.tyczj.extendedcalendarview.ExtendedCalendarView
        android:id="@+id/calendar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

android:layout_height="wrap_content" does not works. Now the ExtendedCalendarView always fill the height of display.

how to solve it?  thanks!

**Comment by ghost** [comment]
What type of error it is shown? in xml it is not showing but when your running in device or emulator it will show the calendar

**Comment by essencer** [comment]
It shows no mistake in XML, but 'android:layout_height="wrap_content"' has no effect on controlling the height.  tyczj says that 'ExtendedCalendarView' need a hard value to set the height.

**Comment by ghost** [comment]
If we don't give any height it will work know like as a 'wrap_content',if you want you can change to 'match_parent' or 'fill_parent' then also it will work.Then what is your problem?
