### ISSUE TITLE
Cursor finalized without prior close()

### ISSUE THREAD

**Issue by essencer** [tyczj/ExtendedCalendarView#84]
when switching to next month or previous month, Log shows below:
![image](https://cloud.githubusercontent.com/assets/9813803/5751449/c6f12146-9c9e-11e4-9562-4c7778ebef4b.png)

![image](https://cloud.githubusercontent.com/assets/9813803/5751456/e32e9712-9c9e-11e4-99c3-7b755a484a19.png)

![image](https://cloud.githubusercontent.com/assets/9813803/5751483/3ce40058-9c9f-11e4-8512-f189c398da73.png)

**Comment by tyczj** [comment]
I made an edit to the day class see if it still happens
