### ISSUE TITLE
Error package on import

### ISSUE THREAD

**Issue by federicoibba** [tyczj/ExtendedCalendarView#86]
Hi,

I was trying to use your library in my project but I got an issue. I import ExtendedCalendarView as a module on Android Studio and I wrote in the main:

> ExtendedCalendarView calendar = (ExtendedCalendarView)findViewById(R.id.calendar);

and import the package like this:

> import com.tyczj.extendedcalendarview.ExtendedCalendarView;

but Android studio told me:

> error: package com.tyczj.extendedcalendarview does not exist
> error: cannot find symbol class ExtendedCalendarView
> error: cannot find symbol class ExtendedCalendarView

What am I doing wront? Thanks!

**Comment by Tazuki** [comment]
habe the same problem with eclipse

...ok had the same prob.
I exportet the Project as *.jar file and imported it in my project as "external jar"
then i could import it in my class =)

hope this helps

**Comment by federicoibba** [comment]
Thanks now it goes! But there is a new issue...with the jar, the project throws an exception:

> java.lang.NoClassDefFoundError: com.tyczj.extendedcalendarview.R$drawable

I've read somewhere that jar doesn't allow drawable objects...

**Comment by Tazuki** [comment]
I also had some Problems with the jar file. I think now i solved the Problem. (Now i deleted the jar and removed it from the list)
When you import the project make sure that you uncheck the checkbox "copy project into workspace". That is very important for eclipse. Had the same problems with other projects too. Let them where they are^^

please feedback if that has helped ;)

**Comment by ibrahim-yener** [comment]
How to get selected date. Or setting different background for certain date?
