### ISSUE TITLE
Need calendar in two applications conflict with instalation

### ISSUE THREAD

**Issue by lrcarrera** [tyczj/ExtendedCalendarView#99]
i dont know why i dont can install the calendar view in two applications i the same device, i have a problem when INSTALL_FAILED_CONFLICTING_PROVIDER, i know if i delete one of apps the application runs, but i will keep two apps
i have this line in two apps. in manifest:
      <provider
            android:name="com.tyczj.extendedcalendarview.CalendarProvider"
            android:authorities="com.tyczj.extendedcalendarview.calendarprovider" />

any help? thanks in advance.

**Comment by tyczj** [comment]
You cannot have two apps that declare the same provider. You need to uninstall one or change the provider of one
